###
# Create a new user: Yogi Bear
POST {{host}}/api/auth/signup HTTP/1.1
content-type: application/json

{
  "firstName": "Yogi",
  "lastName": "Bear",
  "email": "yogibear@mountain.com",
  "password": "Bearpassword123!"
}



###
# Sign in with correct password Yogi Bear
# vscode rest client will save the token cookie for the last signed in user
POST {{host}}/api/auth/signin HTTP/1.1
content-type: application/json

{
  "email": "yogibear@mountain.com",
  "password": "Bearpassword123!"
}



###
# Create a new user: Small Bear
POST {{host}}/api/auth/signup HTTP/1.1
content-type: application/json

{
  "firstName": "Small",
  "lastName": "Bear",
  "email": "Smallbear@mountain.com",
  "password": "Smallpassword123!"
}



###
# Sign in with correct password Small Bear
# vscode rest client will save the token cookie for the last signed in user
POST {{host}}/api/auth/signin HTTP/1.1
content-type: application/json

{
  "email": "Smallbear@mountain.com",
  "password": "Smallpassword123!"
}



###
# Attempt Sign in with incorrect password
POST {{host}}/api/auth/signin HTTP/1.1
content-type: application/json

{
  "email": "bear@mountain.com",
  "password": "Fakepassword123!"
}



###
# Signout
GET {{host}}/api/auth/signout HTTP/1.1
