###
# Get all entries for signed in user
GET http://localhost:3001/api/entries HTTP/1.1

###
# Create an entry as signed in user
POST http://localhost:3001/api/entries HTTP/1.1
Content-Type: application/json

{
  "entryDate": "2020-01-09",
  "diary": "I have stolen picnic baskets."
}
