###
# Get all entries for signed in user
GET {{host}}/api/entries HTTP/1.1

###
# Create an entry as signed in user
POST {{host}}/api/entries HTTP/1.1
Content-Type: application/json

{
  "entryDate": "2020-01-11",
  "diary": "I drink melted snow."
}
