###
# Get all entries
GET http://localhost:3001/api/entries HTTP/1.1

###
# Create an entry
POST http://localhost:3001/api/entries HTTP/1.1
content-type: application/json

{
  "entryDate": "2020-01-09",
  "diary": "I need a break now. Please Selina."
}
